version: '3.8'

services:
  postgres-container:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: james
      POSTGRES_PASSWORD: CupStack54
      POSTGRES_DB: workshops
    ports:
      - "5432:5432"
    networks:
      - yogaempire-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: yogaempire_backend_1
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres-container
      - DB_PORT=5432
      - DB_USER=james
      - DB_PASSWORD=CupStack54
      - DB_NAME=workshops
    depends_on:
      - postgres-container
    volumes:
      - ./backend:/usr/src/app
    networks:
      - yogaempire-network
    command: ["sh", "-c", "until nc -z postgres-container 5432; do echo 'Waiting for database'; node server.js"]

  frontend:
    build:
      context: ./yogaempire-main
    container_name: yogaempire_frontend_1
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - yogaempire-network
    volumes:
      - ./yogaempire-main:/usr/src/app
    command: ["npm", "start"]

networks:
  yogaempire-network:
    driver: bridge

volumes:
  postgres_data:
